colors:
  # Normal colors
  primary:
    background: '0x1d1f21'
    foreground: '0xc5c8c6'
  normal:
    black:   '0x282a22'
    red:     '0xa54242'
    green:   '0x8c9440'
    yellow:  '0xde935f'
    blue:    '0x5f819d'
    magenta: '0x85678f'
    cyan:    '0x5e8d87'
    white:   '0x707880'

# font:
#   bold:
#     family: Meslo LG L for Powerline
#     style: Regular
#   italic:
#     family: Meslo LG L for Powerline
#     style: Italic 
#   normal:
#     family: MesloLGLNerdFont
#     style: Light
#   size: 9
# window:
#   opacity: 0.95
#   padding:
#     x: 5
#     y: 0
# cursor:
#   style: Beam
